import json
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from src.analysis.engine import EPSComponentEngine
from src.analysis.optimizer import EntropyOptimizer
from src.core.logging_setup import setup_logger
from src.analysis.xai import assign_tier

logger = setup_logger("scoring_service")


def softclip_positive(x: np.ndarray, k: float = 3.0) -> np.ndarray:
    """Smooth approximation of max(x, 0): ln(1 + exp(k * x)) / k."""
    return np.log1p(np.exp(np.clip(k * x, -50, 50))) / k


def normalize_zscore_to_01(series: pd.Series) -> pd.Series:
    """Two-step: Z-score then Min-Max to [0,1]."""
    valid = series.dropna()
    if valid.empty:
        return pd.Series(0.0, index=series.index)
    if len(valid) < 2:
        return pd.Series(0.5, index=series.index)
    mu, sigma = valid.mean(), valid.std()
    if sigma == 0:
        return pd.Series(0.5, index=series.index)
    z = (series - mu) / sigma
    z_min, z_max = z.min(), z.max()
    return (z - z_min) / (z_max - z_min + 1e-9)


class ScoringService:
    """Service for calculating state-level EPS rankings."""

    COMP_OPP = ["PD", "GP", "PG", "MMI"]

    def __init__(self, inference_config: dict[str, Any], output_dir: Path):
        self.config = inference_config
        self.output_dir = output_dir
        self.gamma = inference_config.get("gamma", 0.20)
        self.min_sellers = inference_config.get("min_sellers", 5)
        self.n_weeks = inference_config.get("n_weeks", 4)
        scoring_cfg = inference_config.get("scoring", {})
        self.constraints = scoring_cfg.get(
            "constraints",
            {"PD": (0.25, 0.45), "GP": (0.15, 0.35), "PG": (0.15, 0.30), "MMI": (0.05, 0.15)},
        )

    def run_scoring_pipeline(self, features_path: Path, pred_path: Path) -> None:
        logger.info("Starting Scoring Service...")

        # 1. Load & aggregate features, merge predictions
        df_state = self._prepare_state_metrics(features_path, pred_path)

        # 2. Calculate raw components
        raw_df = self._compute_raw(df_state)

        # 3. Normalize components via Z-score -> Min-Max
        norm_df = self._normalize(raw_df)

        # 4. Optimize weights via SLSQP entropy maximization
        w_star = self._optimize(norm_df)

        logger.info(f"Optimal weights: {w_star}")

        # 5. Final ranking
        results = self._rank(norm_df, raw_df, w_star)

        # 6. Save
        self._save(results, w_star)
        logger.info("Scoring Service completed.")

    def _prepare_state_metrics(self, features_path: Path, pred_path: Path) -> pd.DataFrame:
        """Loads features and predictions, aggregates N recent weeks per state."""
        df_feat = pd.read_csv(features_path)

        # Try to load predictions (generated by training pipeline)
        pred_alt = features_path.parent / "predicted_next_week_revenue.csv"
        if pred_alt.exists():
            df_pred = pd.read_csv(pred_alt)
            pred_col = "predicted_next_week_revenue"
        else:
            logger.warning("predicted_next_week_revenue.csv not found, using target_next_revenue")
            df_pred = pd.read_csv(pred_path)
            pred_col = "target_next_revenue"

        # Parse year_week for filtering
        df_feat["week_start"] = pd.to_datetime(
            df_feat["year_week"].astype(str).str.split("/").str[0], errors="coerce"
        )

        # Take N most recent weeks
        latest_weeks = (
            df_feat["week_start"].dropna().drop_duplicates().sort_values().tail(self.n_weeks)
        )

        df_recent = df_feat[df_feat["week_start"].isin(latest_weeks)].copy()

        # Aggregate by state over recent weeks
        df_state = df_recent.groupby("customer_state").agg(
            rev_mean=("revenue", "mean"),
            seller_mean=("unique_sellers", "mean"),
            freight_mean=("avg_freight_value", "mean"),
            population=("population", "last"),
            gdp_per_capita=("gdp_per_capita", "last"),
            revenue_rolling_8=("revenue_rolling_8", "last"),
        ).reset_index()

        # Merge predictions
        if "customer_state" not in df_pred.columns and "state" in df_pred.columns:
            df_pred = df_pred.rename(columns={"state": "customer_state"})
        pred_col_renamed = "predicted_next_week_revenue" if pred_col == "predicted_next_week_revenue" else pred_col
        df_state = df_state.merge(
            df_pred[["customer_state", pred_col_renamed]],
            on="customer_state", how="left"
        )
        df_state = df_state.rename(columns={pred_col_renamed: "predicted_next_week_revenue"})

        logger.info(f"Prepared data for {len(df_state)} states.")
        return df_state

    def _compute_raw(self, df: pd.DataFrame) -> pd.DataFrame:
        """Computes raw components matching original EPS engine."""
        out = pd.DataFrame({"customer_state": df["customer_state"]})

        predicted_rev = df["predicted_next_week_revenue"].fillna(0)
        r4w = df["rev_mean"]
        r8w = df["revenue_rolling_8"]

        # PD: Predicted Demand
        out["PD_raw"] = 0.5 * np.log1p(predicted_rev) + 0.5 * np.log1p(r4w)

        # GP: Growth Potential (cycle-over-cycle)
        nat_median_r8w = r8w.median()
        epsilon = nat_median_r8w * 0.01 if pd.notna(nat_median_r8w) else 1.0
        r8w_safe = r8w.clip(lower=epsilon)
        out["GP_raw"] = ((r4w - r8w_safe) / r8w_safe).clip(-1, 1).fillna(0)
        out["data_sparse"] = r8w < r8w.quantile(0.05)

        # PG: Penetration Gap
        nat_gdp_pc = np.average(df["gdp_per_capita"], weights=df["population"])
        gdp_weight = df["gdp_per_capita"] / nat_gdp_pc
        nat_rev_pc = r4w.sum() / df["population"].sum()
        expected_rev = df["population"] * nat_rev_pc * gdp_weight
        pg_raw = (expected_rev - r4w) / (expected_rev + 1e-9)
        out["PG_raw"] = pg_raw
        out["PG_raw_soft"] = softclip_positive(pg_raw.values)

        # MMI: Market Momentum Index
        seller_ok = df["seller_mean"] >= self.min_sellers
        rev_per_seller = r4w / df["seller_mean"].replace(0, np.nan)
        out["MMI_raw"] = np.where(seller_ok, np.log1p(rev_per_seller), np.nan)

        # LC: Logistics Cost
        out["LC_raw"] = df["freight_mean"].values

        return out

    def _normalize(self, raw_df: pd.DataFrame) -> pd.DataFrame:
        """Z-score -> Min-Max normalization + median imputation for MMI."""
        norm = pd.DataFrame({"customer_state": raw_df["customer_state"]})

        norm["PD"] = normalize_zscore_to_01(raw_df["PD_raw"])
        norm["GP"] = normalize_zscore_to_01(raw_df["GP_raw"])
        norm["PG"] = normalize_zscore_to_01(raw_df["PG_raw_soft"])
        norm["MMI"] = normalize_zscore_to_01(raw_df["MMI_raw"])
        norm["MMI"] = norm["MMI"].fillna(norm["MMI"].median())
        norm["LC"] = normalize_zscore_to_01(raw_df["LC_raw"])

        for col in self.COMP_OPP + ["LC"]:
            norm[col] = norm[col].clip(0.0, 1.0)

        return norm

    def _optimize(self, norm_df: pd.DataFrame) -> dict[str, float]:
        """Runs SLSQP entropy maximization to find optimal weights."""
        bounds = [self.constraints[c] for c in self.COMP_OPP]
        comp_matrix = norm_df[self.COMP_OPP].values

        w_star = EntropyOptimizer.find_optimal_weights(comp_matrix, bounds)

        return {c: float(w) for c, w in zip(self.COMP_OPP, w_star)}

    def _rank(self, norm_df: pd.DataFrame, raw_df: pd.DataFrame, w_star: dict[str, float]) -> pd.DataFrame:
        """Calculates final EPS score and rank."""
        res = norm_df.copy()
        res["customer_state"] = norm_df["customer_state"]
        w_arr = np.array([w_star[c] for c in self.COMP_OPP])

        opp_score = (res[self.COMP_OPP].values * w_arr).sum(axis=1)
        risk_adj = 1.0 - self.gamma * res["LC"].values
        eps_raw = opp_score * risk_adj

        eps_min, eps_max = eps_raw.min(), eps_raw.max()
        res["EPS_score"] = (eps_raw - eps_min) / (eps_max - eps_min + 1e-9) * 100.0
        res["EPS_rank"] = pd.Series(res["EPS_score"]).rank(ascending=False).astype(int).values
        res["OPP_score"] = opp_score
        res["Risk_Adj"] = risk_adj
        res["risk_penalty_pct"] = self.gamma * res["LC"] * 100

        for c in self.COMP_OPP:
            res[f"{c}_norm"] = res[c]
        res["LC_norm"] = res["LC"]
        res["data_sparse"] = raw_df["data_sparse"].values

        for i, c in enumerate(self.COMP_OPP):
            res[f"w_{c}"] = round(w_star[c], 4)

        # Derived columns
        contribs = res[[f"{c}_norm" for c in self.COMP_OPP]].values * w_arr
        for i, c in enumerate(self.COMP_OPP):
            res[f"contrib_{c}"] = contribs[:, i]
            res[f"contrib_pct_{c}"] = (contribs[:, i] / (opp_score + 1e-9)) * 100.0

        res["dominant_component"] = res[[f"contrib_{c}" for c in self.COMP_OPP]].idxmax(axis=1).str.replace("contrib_", "")
        res["weakest_component"] = res[[f"contrib_{c}" for c in self.COMP_OPP]].idxmin(axis=1).str.replace("contrib_", "")

        res["tier"] = res["EPS_rank"].apply(lambda r: assign_tier(r, len(res)))

        STATE_MAP = {
            "AC": "Acre", "AL": "Alagoas", "AP": "Amapá", "AM": "Amazonas",
            "BA": "Bahia", "CE": "Ceará", "DF": "Distrito Federal", "ES": "Espírito Santo",
            "GO": "Goiás", "MA": "Maranhão", "MT": "Mato Grosso", "MS": "Mato Grosso do Sul",
            "MG": "Minas Gerais", "PA": "Pará", "PB": "Paraíba", "PR": "Paraná",
            "PE": "Pernambuco", "PI": "Piauí", "RJ": "Rio de Janeiro", "RN": "Rio Grande do Norte",
            "RS": "Rio Grande do Sul", "RO": "Rondônia", "RR": "Roraima", "SC": "Santa Catarina",
            "SP": "São Paulo", "SE": "Sergipe", "TO": "Tocantins",
        }
        res["state_display"] = res["customer_state"].map(STATE_MAP).fillna(res["customer_state"])

        return res.sort_values("EPS_rank").reset_index(drop=True)

    def _save(self, df: pd.DataFrame, w_star: dict[str, float]) -> None:
        self.output_dir.mkdir(parents=True, exist_ok=True)
        df.to_csv(self.output_dir / "eps_results.csv", index=False)
        with open(self.output_dir / "w_star.json", "w") as f:
            json.dump({"w_star": w_star, "gamma": self.gamma}, f, indent=2)
        logger.info(f"Saved EPS results and weights to {self.output_dir}")
